#!/bin/sh

case "$2" in
	up|vpn-up)
		if [ "$DHCP4_REQUESTED_NTP_SERVERS" != "1" ] &&
		   [ "$DHCP6_REQUESTED_NTP_SERVERS" != "1" ]; then
			exit 0
		fi

		# shellcheck disable=SC2034
		reason=BOUND
		;;
	down|vpn-down)
		# shellcheck disable=SC2034
		reason=RELEASE
		;;
	*)
		exit 0
		;;
esac

test -f /etc/dhcp/dhclient-exit-hooks.d/ntpsec-ntpdate || exit 0
. /etc/dhcp/dhclient-exit-hooks.d/ntpsec-ntpdate
